services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"  # Port for RabbitMQ management UI
      - "5672:5672"    # Port for RabbitMQ

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  flower:
    image: mher/flower
    command: ["--broker=amqp://user:password@rabbitmq:5672//"]
    ports:
      - "5555:5555"

  web:
    build: .
    command: ["sh", "-c", "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 task_manager.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - elasticsearch

  celery:
    build: .
    command: celery -A task_manager worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

  celery-beat:
    build: .
    command: celery -A task_manager beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data:
  es_data:
